///parse(SVG)
payload=string_remove_whitespace(argument0);
if(button_DOC.enabled){
payload=string_remove_DOC(payload);
}
if(button_XML_dec.enabled){
payload=string_remove_XML(payload);
}
if(button_comments.enabled){
payload=string_remove_comments(payload);
}
if(button_CSS_padding.enabled){
payload=string_remove_CSS_padding(payload);
}
if(button_version.enabled){
}
if(button_metadata.enabled){
payload=string_metadata(payload);
}
if(button_class_names.enabled){
}
if(button_serialize_IDs.enabled){
}
if(button_groups.enabled){
}
if(button_styles.enabled){
}
if(button_weld_paths.enabled){
}
if(button_human_readable.enabled){
}
return payload;
