///parse(SVG)
payload=string_remove_whitespace(argument0);
if(button_DOC.enabled){
}
if(button_version.enabled){
}
if(button_comments.enabled){
}
if(button_CSS_padding.enabled){
}
if(button_class_names.enabled){
}
if(button_serialize_IDs.enabled){
}
if(button_groups.enabled){
}
if(button_styles.enabled){
show_debug_message("enabled");
}
if(button_weld_paths.enabled){
}
if(button_human_readable.enabled){
}
return payload;
